### ISSUE TITLE
HPB ignores VNIC type direct (both unified and traditional mode mech drivers)

### ISSUE THREAD

**Issue by irathore** [noironetworks/neutron#6]
SRIOV uses direct VNIC_TYPE (VNIC_DIRECT). But our mech driver only handles VNIC_NORMAL resulting in local vlan segment not being created.

We need this for supporting SRIOV wit HPB.

**Comment by amittbose** [comment]
Fix posted for review: https://review.openstack.org/#/c/450476

**Comment by amittbose** [comment]
Fix merged
