### ISSUE TITLE
Need to be able to have sriov and openvswitch on the same copute node

### ISSUE THREAD

**Issue by irathore** [noironetworks/neutron#8]
I have a single compute node with SRIOV and openvswitch (this is the use case for a customer).

SRIOV (physnet3)  is connected to 401/1/21 and the openvswitch (physnet2) is connected to 402/1/21. There does not seem to be a way of specifying the two links. Whatever I do, it will only create static binding for either 401/1/21 or 402/1/21. So I guess with  this method we can only combine opflex and sriov on a single host. I am thinking correctly?

[apic_switch:401]
bm2.sys.cisco.com = 1/21
[apic_switch:402]
bm1.sys.cisco.com = 1/31

# APIC domains are specified by the following sections:
[apic_physdom:BM-Phys]

[apic_physical_network:physnet1]
hosts=bm1.sys.cisco.com
segment_type=vlan

[apic_physical_network:physnet3]
hosts=bm2.sys.cisco.com
segment_type=vlan

**Comment by amittbose** [comment]
Filed the issue under repo noironetworks/support so that Mandeep can track it (https://github.com/noironetworks/support/issues/515)
